### PR TITLE
Include HTML

### PR DESCRIPTION
**Pull request by brunowego**
:+1:

### CODE REVIEW

**Comment by piascikj** [comment]
Bruno, For html there's some changes that have to be made in lib/file.js.  HTML has only block comments.  So it would look more like this...
```
{"name": "html", "symbol":"//", "block": {"start": "<!--", "end": "-->", "ignore": "-"}}
```
But this would only show tasks in html comments, and single line javascript comments.  In reality there are three ways a comment can be identified in an html file.

## javascript line
`// TODO: bla bla bla`

## javascript block
```
/*
TODO: bla bla bla
*/
```

## html block
```
<!--
TODO: bla bla bla
-->
```

file.js will have to be changed to allow multiple block styles in a language.

**Comment by piascikj** [comment]
Without any changes to languages tasks that start with `#` will be recognized.

**Comment by brunowego** [comment]
Cool, I understand, will be necessary to make some adjustments to the project before working with HTML. Thank you.

**Comment by piascikj** [comment]
TODO: Allow languages to have multiple block comment styles, like html gh:13 id:2
    [**lib/file.js:298**](https://github.com/imdone/imdone-core/blob/master/lib/file.js#L298)  
@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](http://localhost:3000)

**Comment by piascikj** [comment]
TODO: Allow languages to have multiple block comment styles, like html gh:13 id:2
    [**lib/file.js:298**](https://github.com/imdone/imdone-core/blob/master/lib/file.js#L298)  
@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](http://localhost:3000)

**Comment by piascikj** [comment]
TODO: Allow languages to have multiple block comment styles, like html gh:13 id:13
    [**lib/file.js:298**](https://github.com/imdone/imdone-core/blob/master/lib/file.js#L298)  
@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Pull request closed without merging**
