### PR TITLE
Don’t add a priority to tasks that don’t already have one. (Closes #7)

### LINKED ISSUE #7: unnecessary changes
I'm editing coffeescript and I have a line like this:
```
  # TODO: remove this method and bump the `vim-mode` service version number.
```
It shows up in the iMDone list and that's good. But if I drag it a bit and release it (leaving it in the same place in the same TODO list), it becomes 
```
  # #TODO:0 remove this method and bump the `vim-mode` service version number.
```
Can something be done about the new `#` character? And if I drag an item and release it in the same place, could this avoid triggering priority changes? 

I have very little experience with tools like iMDone, so please treat the last one as a very tentative suggestion: could iMDone treat TODO without priority as an item with a priority fixed at 0, only ever changing its priority if I drag this item to a new place after an item with a priority? I would like that as a configuration option. 

I would be willing to look into submitting PRs for these, but it would take me some time.

### PR DESCRIPTION
**Pull request by claytonrcarter**
This an attempt to treat priorities as optional parts of tasks.  Tasks without a priority (ie `order`) have their `order` set to an empty string (instead of `0`).  When `order` is updated, we skip those that are just an empty string, and when tasks are modified or output, we skip the `:<order>` part of the format string for tasks whose order is an empty string.

I'm not very familiar with Grunt, and I was not able to figure out to make new tests for this, but all existing tests appear to pass and using this with `imdone-atom` within Atom seemed to work: tasks with no priority were left with no priority when they were moved between lists and tasks with priority were updated correctly.

### CODE REVIEW

**Comment by piascikj** [comment]
Thanks for taking this on.  I'll have a look and provide some commentary.  I'd really like to get this implemented for code style tasks.

**Comment by claytonrcarter** [comment]
@piascikj I overlooked something: when a list is updated, this code will remove the colon from all tasks that don't have a priority, which will result (the first time, anyway) in a lot of changes throughout a repo if the author happens to have mixed tasks with colons and some without.  I would like to update this PR to try to keep the original format intact, but it might not be until next week.

**Comment by claytonrcarter** [comment]
@piascikj Sorry for delay on this.  This PR updates the regex for code tasks and, as well as the Task object.  The idea is that code tasks with out a priority also do not need a colon, so we have three "formats" for code style tasks:

* list + colon + priority + task, etc
* list + colon + task, etc
* list + task, etc

These changes pass spec, but I wasn't sure how to write a spec to test these changes, so that piece is currently incomplete.

**Comment by piascikj** [comment]
I tried this out and like it, but I would prefer it to be a configuration setting, like `keepEmptyPriority: true` in `.imdone/config.json`  if you can make that change and it passes the test suite, I'll merge.

**Comment by claytonrcarter** [comment]
Done.  Things to note:
1. I took your suggestion verbatim and named the config setting `keepEmptyPriorities`. It defaults to `false`.
2. I made a minor update to the API for `File.prototype.extractTasksInNonCodeFile`, `File.prototype.extractHashStyleTasks` and `File.prototype.extractLinkStyleTasks` so that `config` could be passed into them.  This was already being done for `File.prototype.extractTasksInCodeFile` and `File.prototype.extractCodeStyleTasks` so it seemed reasonable.
3. I updated the task regexs to make priorities optional for hash and link style tasks.  Colons are also optional for link tasks.  (The code to support empty priorities was already in place; I had just forgotten to update the regexs.)  I tried to make colons optional for hash tasks, but it kept turning all of my CSS id selectors (ie `#elementID`) into tasks!  Funny.
4. Updated README.md with new examples for hash and link tasks w/o priorities.

**Pull request merged**
